### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Zhuangmoumou** [qy527145/openai_token#7]
内容
Traceback (most recent call last):
  File "/workspace/openai_token/openai_token.py", line 258, in <module>
    cli()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/openai_token/openai_token.py", line 243, in cli
    print({"refresh_token": obj.get_refresh_token()})
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/openai_token/openai_token.py", line 48, in get_refresh_token
    self.ensure_refresh_token()
  File "/workspace/openai_token/openai_token.py", line 91, in ensure_refresh_token
    preauth_cookie = self.get_preauth_cookie()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/openai_token/openai_token.py", line 164, in get_preauth_cookie
    raise Exception('抓取preauth_cookie失败')
Exception: 抓取preauth_cookie失败

**Comment by qy527145** [comment]
preauth_cookie需要使用ios设备拿到的device_token，具体方法看：https://linux.do/t/topic/58580

**Comment by qy527145** [comment]
参考https://github.com/0x676e67/devicecheck
